DROP TABLE IF EXISTS xmldb_suiyue.abyss_leader_skill;
CREATE TABLE xmldb_suiyue.abyss_leader_skill (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(21) COMMENT 'name',
    `_dev_name_` VARCHAR(18) COMMENT '_dev_name_',
    `forceskill_min_member` VARCHAR(2) COMMENT 'forceskill_min_member',
    `forceskill_min_rank_01` VARCHAR(2) COMMENT 'forceskill_min_rank_01',
    `forceskill01_01` VARCHAR(19) COMMENT 'forceskill01_01',
    `forceskill01_02` VARCHAR(17) COMMENT 'forceskill01_02',
    `forceskill01_03` VARCHAR(14) COMMENT 'forceskill01_03',
    `forceskill_min_rank_02` VARCHAR(2) COMMENT 'forceskill_min_rank_02',
    `forceskill02_01` VARCHAR(19) COMMENT 'forceskill02_01',
    `forceskill02_02` VARCHAR(17) COMMENT 'forceskill02_02',
    `forceskill02_03` VARCHAR(14) COMMENT 'forceskill02_03',
    `forceskill_min_rank_03` VARCHAR(2) COMMENT 'forceskill_min_rank_03',
    `forceskill03_01` VARCHAR(19) COMMENT 'forceskill03_01',
    `forceskill03_02` VARCHAR(17) COMMENT 'forceskill03_02',
    `forceskill03_03` VARCHAR(14) COMMENT 'forceskill03_03',
    `unionskill_min_member` VARCHAR(2) COMMENT 'unionskill_min_member',
    `unionskill_min_rank_01` VARCHAR(2) COMMENT 'unionskill_min_rank_01',
    `unionskill01` VARCHAR(12) COMMENT 'unionskill01',
    `unionskill_min_rank_02` VARCHAR(2) COMMENT 'unionskill_min_rank_02',
    `unionskill02` VARCHAR(12) COMMENT 'unionskill02',
    `unionskill_min_rank_03` VARCHAR(2) COMMENT 'unionskill_min_rank_03',
    `unionskill03` VARCHAR(12) COMMENT 'unionskill03',
    `groupskill_min_member` VARCHAR(2) COMMENT 'groupskill_min_member',
    `groupskill_min_rank_01` VARCHAR(2) COMMENT 'groupskill_min_rank_01',
    `groupskill01` VARCHAR(21) COMMENT 'groupskill01',
    `groupskill_min_rank_02` VARCHAR(2) COMMENT 'groupskill_min_rank_02',
    `groupskill02` VARCHAR(21) COMMENT 'groupskill02',
    `groupskill_min_rank_03` VARCHAR(2) COMMENT 'groupskill_min_rank_03',
    `groupskill03` VARCHAR(21) COMMENT 'groupskill03'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'abyss_leader_skill';

