DROP TABLE IF EXISTS xmldb_suiyue.familiars;
CREATE TABLE xmldb_suiyue.familiars (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(24) COMMENT 'name',
    `desc` VARCHAR(32) COMMENT 'desc',
    `dir` VARCHAR(27) COMMENT 'dir',
    `mesh` VARCHAR(18) COMMENT 'mesh',
    `wing` VARCHAR(14) COMMENT 'wing',
    `fgroup_set` VARCHAR(26) COMMENT 'fgroup_set',
    `tier_grade` VARCHAR(1) COMMENT 'tier_grade',
    `star_grade` VARCHAR(1) COMMENT 'star_grade',
    `is_only_feeds` VARCHAR(5) COMMENT 'is_only_feeds',
    `use_func_option` VARCHAR(5) COMMENT 'use_func_option',
    `physical_bonus_attr1` VARCHAR(10) COMMENT 'physical_bonus_attr1',
    `magical_bonus_attr1` VARCHAR(10) COMMENT 'magical_bonus_attr1',
    `fskill01` VARCHAR(20) COMMENT 'fskill01',
    `usefskill01_energy` VARCHAR(3) COMMENT 'usefskill01_energy',
    `growth_pt` VARCHAR(5) COMMENT 'growth_pt',
    `physical_bonus_attr2` VARCHAR(12) COMMENT 'physical_bonus_attr2',
    `magical_bonus_attr2` VARCHAR(21) COMMENT 'magical_bonus_attr2',
    `physical_bonus_attr3` VARCHAR(11) COMMENT 'physical_bonus_attr3',
    `magical_bonus_attr3` VARCHAR(22) COMMENT 'magical_bonus_attr3',
    `physical_bonus_attr4` VARCHAR(15) COMMENT 'physical_bonus_attr4',
    `magical_bonus_attr4` VARCHAR(18) COMMENT 'magical_bonus_attr4',
    `max_growth_value` VARCHAR(5) COMMENT 'max_growth_value',
    `growth_cost` VARCHAR(6) COMMENT 'growth_cost',
    `evolve_item` VARCHAR(24) COMMENT 'evolve_item',
    `evolve_item_num` VARCHAR(4) COMMENT 'evolve_item_num',
    `evolve_cost` VARCHAR(9) COMMENT 'evolve_cost',
    `fskill02` VARCHAR(26) COMMENT 'fskill02',
    `usefskill02_energy` VARCHAR(3) COMMENT 'usefskill02_energy'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'familiars';

