DROP TABLE IF EXISTS xmldb_suiyue.instance_creation;
CREATE TABLE xmldb_suiyue.instance_creation (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(42) COMMENT 'name',
    `worldname` VARCHAR(23) COMMENT 'worldname',
    `type` VARCHAR(21) COMMENT 'type',
    `spawn_page` VARCHAR(2) COMMENT 'spawn_page',
    `deathexppenalty` VARCHAR(5) COMMENT 'deathexppenalty',
    `deathappenalty` VARCHAR(5) COMMENT 'deathappenalty',
    `start_point_alias_01` VARCHAR(32) COMMENT 'start_point_alias_01',
    `start_point_alias_02` VARCHAR(32) COMMENT 'start_point_alias_02',
    `resurrect_point_alias_01` VARCHAR(32) COMMENT 'resurrect_point_alias_01',
    `resurrect_point_alias_02` VARCHAR(32) COMMENT 'resurrect_point_alias_02',
    `resurrect_sp` VARCHAR(4) COMMENT 'resurrect_sp',
    `requisite_light` VARCHAR(33) COMMENT 'requisite_light',
    `requisite_dark` VARCHAR(33) COMMENT 'requisite_dark',
    `inside_group` VARCHAR(4) COMMENT 'inside_group',
    `exceptresurhpmppenalty` VARCHAR(21) COMMENT 'exceptresurhpmppenalty',
    `exceptresurdebuffpenalty` VARCHAR(21) COMMENT 'exceptresurdebuffpenalty',
    `rate_id` VARCHAR(3) COMMENT 'rate_id',
    `exp_bonus` VARCHAR(3) COMMENT 'exp_bonus',
    `drop_bonus` VARCHAR(1) COMMENT 'drop_bonus',
    `bonusattr` VARCHAR(29) COMMENT 'bonusattr',
    `legion_member_only` VARCHAR(4) COMMENT 'legion_member_only',
    `keep_group` VARCHAR(4) COMMENT 'keep_group',
    `rank_id` VARCHAR(1) COMMENT 'rank_id',
    `ap_bonus` VARCHAR(4) COMMENT 'ap_bonus'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'instance_creation';

