DROP TABLE IF EXISTS xmldb_suiyue.item_luna;
CREATE TABLE xmldb_suiyue.item_luna (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(22) COMMENT 'name',
    `desc` VARCHAR(20) COMMENT 'desc',
    `item_type` VARCHAR(6) COMMENT 'item_type',
    `price` VARCHAR(1) COMMENT 'price',
    `luna_price` VARCHAR(2) COMMENT 'luna_price',
    `extra_inventory` VARCHAR(1) COMMENT 'extra_inventory',
    `max_stack_count` VARCHAR(5) COMMENT 'max_stack_count',
    `quality` VARCHAR(6) COMMENT 'quality',
    `level` VARCHAR(1) COMMENT 'level',
    `lore` VARCHAR(5) COMMENT 'lore',
    `can_exchange` VARCHAR(4) COMMENT 'can_exchange',
    `can_sell_to_npc` VARCHAR(5) COMMENT 'can_sell_to_npc',
    `can_deposit_to_character_warehouse` VARCHAR(4) COMMENT 'can_deposit_to_character_warehouse',
    `can_deposit_to_account_warehouse` VARCHAR(4) COMMENT 'can_deposit_to_account_warehouse',
    `can_deposit_to_guild_warehouse` VARCHAR(4) COMMENT 'can_deposit_to_guild_warehouse',
    `breakable` VARCHAR(4) COMMENT 'breakable',
    `soul_bind` VARCHAR(5) COMMENT 'soul_bind',
    `remove_when_logout` VARCHAR(5) COMMENT 'remove_when_logout',
    `quest` VARCHAR(1) COMMENT 'quest',
    `gender_permitted` VARCHAR(3) COMMENT 'gender_permitted',
    `warrior` VARCHAR(1) COMMENT 'warrior',
    `scout` VARCHAR(1) COMMENT 'scout',
    `mage` VARCHAR(1) COMMENT 'mage',
    `cleric` VARCHAR(1) COMMENT 'cleric',
    `engineer` VARCHAR(1) COMMENT 'engineer',
    `artist` VARCHAR(1) COMMENT 'artist',
    `fighter` VARCHAR(1) COMMENT 'fighter',
    `knight` VARCHAR(1) COMMENT 'knight',
    `assassin` VARCHAR(1) COMMENT 'assassin',
    `ranger` VARCHAR(1) COMMENT 'ranger',
    `wizard` VARCHAR(1) COMMENT 'wizard',
    `elementalist` VARCHAR(1) COMMENT 'elementalist',
    `chanter` VARCHAR(1) COMMENT 'chanter',
    `priest` VARCHAR(1) COMMENT 'priest',
    `gunner` VARCHAR(1) COMMENT 'gunner',
    `bard` VARCHAR(1) COMMENT 'bard',
    `rider` VARCHAR(1) COMMENT 'rider',
    `cash_item` VARCHAR(1) COMMENT 'cash_item',
    `can_split` VARCHAR(4) COMMENT 'can_split',
    `item_drop_permitted` VARCHAR(5) COMMENT 'item_drop_permitted',
    `race_permitted` VARCHAR(16) COMMENT 'race_permitted'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'item_luna';

