DROP TABLE IF EXISTS xmldb_suiyue.skill_qualification;
CREATE TABLE xmldb_suiyue.skill_qualification (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(30) COMMENT 'name',
    `skill_advancement` VARCHAR(1) COMMENT 'skill_advancement',
    `qualification_race1` VARCHAR(8) COMMENT 'qualification_race1',
    `qualification_class1` VARCHAR(13) COMMENT 'qualification_class1',
    `qualification_value1` VARCHAR(2) COMMENT 'qualification_value1',
    `advancement_rate1` VARCHAR(1) COMMENT 'advancement_rate1',
    `advancement_max1` VARCHAR(2) COMMENT 'advancement_max1',
    `qualification_race2` VARCHAR(3) COMMENT 'qualification_race2',
    `qualification_race3` VARCHAR(3) COMMENT 'qualification_race3',
    `qualification_race4` VARCHAR(3) COMMENT 'qualification_race4',
    `qualification_race5` VARCHAR(3) COMMENT 'qualification_race5',
    `qualification_race6` VARCHAR(3) COMMENT 'qualification_race6',
    `qualification_race7` VARCHAR(3) COMMENT 'qualification_race7',
    `qualification_race8` VARCHAR(3) COMMENT 'qualification_race8',
    `qualification_class2` VARCHAR(7) COMMENT 'qualification_class2',
    `qualification_value2` VARCHAR(2) COMMENT 'qualification_value2',
    `advancement_rate2` VARCHAR(2) COMMENT 'advancement_rate2',
    `advancement_max2` VARCHAR(2) COMMENT 'advancement_max2',
    `qualification_class3` VARCHAR(13) COMMENT 'qualification_class3',
    `qualification_value3` VARCHAR(2) COMMENT 'qualification_value3',
    `advancement_rate3` VARCHAR(2) COMMENT 'advancement_rate3',
    `advancement_max3` VARCHAR(2) COMMENT 'advancement_max3',
    `qualification_class4` VARCHAR(8) COMMENT 'qualification_class4',
    `qualification_value4` VARCHAR(2) COMMENT 'qualification_value4',
    `advancement_rate4` VARCHAR(2) COMMENT 'advancement_rate4',
    `advancement_max4` VARCHAR(2) COMMENT 'advancement_max4',
    `qualification_class5` VARCHAR(6) COMMENT 'qualification_class5',
    `qualification_value5` VARCHAR(2) COMMENT 'qualification_value5',
    `advancement_rate5` VARCHAR(1) COMMENT 'advancement_rate5',
    `advancement_max5` VARCHAR(2) COMMENT 'advancement_max5',
    `qualification_class6` VARCHAR(7) COMMENT 'qualification_class6',
    `qualification_value6` VARCHAR(2) COMMENT 'qualification_value6',
    `advancement_rate6` VARCHAR(1) COMMENT 'advancement_rate6',
    `advancement_max6` VARCHAR(2) COMMENT 'advancement_max6',
    `qualification_class7` VARCHAR(6) COMMENT 'qualification_class7',
    `qualification_value7` VARCHAR(2) COMMENT 'qualification_value7',
    `advancement_rate7` VARCHAR(1) COMMENT 'advancement_rate7',
    `advancement_max7` VARCHAR(2) COMMENT 'advancement_max7',
    `qualification_class8` VARCHAR(13) COMMENT 'qualification_class8',
    `qualification_value8` VARCHAR(2) COMMENT 'qualification_value8',
    `advancement_rate8` VARCHAR(1) COMMENT 'advancement_rate8',
    `advancement_max8` VARCHAR(2) COMMENT 'advancement_max8'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'skill_qualification';

