DROP TABLE IF EXISTS xmldb_suiyue.toypet_feed;
CREATE TABLE xmldb_suiyue.toypet_feed (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` VARCHAR(35) COMMENT 'name',
    `limit_love_count` VARCHAR(3) COMMENT 'limit_love_count',
    `love_flavor_id_1` VARCHAR(4) COMMENT 'love_flavor_id_1',
    `love_flavor_reward_1` VARCHAR(27) COMMENT 'love_flavor_reward_1',
    `love_flavor_id_2` VARCHAR(4) COMMENT 'love_flavor_id_2',
    `love_flavor_reward_2` VARCHAR(27) COMMENT 'love_flavor_reward_2',
    `feeding_count` VARCHAR(3) COMMENT 'feeding_count',
    `favorite_flavor_id` VARCHAR(4) COMMENT 'favorite_flavor_id',
    `feeding_cooltime` VARCHAR(4) COMMENT 'feeding_cooltime',
    `favorite_flavor_reward_1_5` VARCHAR(46) COMMENT 'favorite_flavor_reward_1_5',
    `favorite_flavor_reward_6_10` VARCHAR(46) COMMENT 'favorite_flavor_reward_6_10',
    `favorite_flavor_reward_11_15` VARCHAR(46) COMMENT 'favorite_flavor_reward_11_15',
    `favorite_flavor_reward_16_20` VARCHAR(46) COMMENT 'favorite_flavor_reward_16_20',
    `favorite_flavor_reward_21_25` VARCHAR(46) COMMENT 'favorite_flavor_reward_21_25',
    `favorite_flavor_reward_26_30` VARCHAR(46) COMMENT 'favorite_flavor_reward_26_30',
    `favorite_flavor_reward_31_35` VARCHAR(46) COMMENT 'favorite_flavor_reward_31_35',
    `favorite_flavor_reward_36_40` VARCHAR(46) COMMENT 'favorite_flavor_reward_36_40',
    `favorite_flavor_reward_41_45` VARCHAR(46) COMMENT 'favorite_flavor_reward_41_45',
    `favorite_flavor_reward_46_50` VARCHAR(46) COMMENT 'favorite_flavor_reward_46_50',
    `favorite_flavor_reward_51_55` VARCHAR(46) COMMENT 'favorite_flavor_reward_51_55',
    `favorite_flavor_reward_56_60` VARCHAR(46) COMMENT 'favorite_flavor_reward_56_60',
    `love_flavor_id_3` VARCHAR(4) COMMENT 'love_flavor_id_3',
    `love_flavor_reward_3` VARCHAR(27) COMMENT 'love_flavor_reward_3',
    `love_flavor_id_4` VARCHAR(3) COMMENT 'love_flavor_id_4',
    `love_flavor_reward_4` VARCHAR(20) COMMENT 'love_flavor_reward_4'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'toypet_feed';

