DROP TABLE IF EXISTS xmldb_suiyue.quest;
CREATE TABLE xmldb_suiyue.quest (
    `id` VARCHAR(255) PRIMARY KEY COMMENT 'id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `name` MEDIUMTEXT COMMENT 'name',
    `dev_name` MEDIUMTEXT COMMENT 'dev_name',
    `desc` MEDIUMTEXT COMMENT 'desc',
    `category1` MEDIUMTEXT COMMENT 'category1',
    `category2` MEDIUMTEXT COMMENT 'category2',
    `f_mission` MEDIUMTEXT COMMENT 'f_mission',
    `max_repeat_count` MEDIUMTEXT COMMENT 'max_repeat_count',
    `client_level` MEDIUMTEXT COMMENT 'client_level',
    `minlevel_permitted` MEDIUMTEXT COMMENT 'minlevel_permitted',
    `maxlevel_permitted` MEDIUMTEXT COMMENT 'maxlevel_permitted',
    `gender_permitted` MEDIUMTEXT COMMENT 'gender_permitted',
    `bm_restrict_category` MEDIUMTEXT COMMENT 'bm_restrict_category',
    `reward_exp1` MEDIUMTEXT COMMENT 'reward_exp1',
    `reward_gold1` MEDIUMTEXT COMMENT 'reward_gold1',
    `class_permitted` MEDIUMTEXT COMMENT 'class_permitted',
    `race_permitted` MEDIUMTEXT COMMENT 'race_permitted',
    `cannot_giveup` MEDIUMTEXT COMMENT 'cannot_giveup',
    `cannot_share` MEDIUMTEXT COMMENT 'cannot_share',
    `__type_desc__` MEDIUMTEXT COMMENT '__type_desc__',
    `collect_progress` MEDIUMTEXT COMMENT 'collect_progress',
    `collect_item1` MEDIUMTEXT COMMENT 'collect_item1',
    `drop_monster_1` MEDIUMTEXT COMMENT 'drop_monster_1',
    `drop_item_1` MEDIUMTEXT COMMENT 'drop_item_1',
    `drop_prob_1` MEDIUMTEXT COMMENT 'drop_prob_1',
    `drop_each_member_1` MEDIUMTEXT COMMENT 'drop_each_member_1',
    `selectable_reward_item1_1` MEDIUMTEXT COMMENT 'selectable_reward_item1_1',
    `selectable_reward_item1_2` MEDIUMTEXT COMMENT 'selectable_reward_item1_2',
    `selectable_reward_item1_3` MEDIUMTEXT COMMENT 'selectable_reward_item1_3',
    `check_item1_1` MEDIUMTEXT COMMENT 'check_item1_1',
    `drop_monster_2` MEDIUMTEXT COMMENT 'drop_monster_2',
    `drop_item_2` MEDIUMTEXT COMMENT 'drop_item_2',
    `drop_prob_2` MEDIUMTEXT COMMENT 'drop_prob_2',
    `drop_each_member_2` MEDIUMTEXT COMMENT 'drop_each_member_2',
    `selectable_reward_item1_4` MEDIUMTEXT COMMENT 'selectable_reward_item1_4',
    `selectable_reward_item1_5` MEDIUMTEXT COMMENT 'selectable_reward_item1_5',
    `selectable_reward_item1_6` MEDIUMTEXT COMMENT 'selectable_reward_item1_6',
    `reward_title1` MEDIUMTEXT COMMENT 'reward_title1',
    `use_class_reward` MEDIUMTEXT COMMENT 'use_class_reward',
    `reward_exp2` MEDIUMTEXT COMMENT 'reward_exp2',
    `reward_exp3` MEDIUMTEXT COMMENT 'reward_exp3',
    `reward_exp4` MEDIUMTEXT COMMENT 'reward_exp4',
    `reward_exp5` MEDIUMTEXT COMMENT 'reward_exp5',
    `reward_exp6` MEDIUMTEXT COMMENT 'reward_exp6',
    `fighter_selectable_reward` MEDIUMTEXT COMMENT 'fighter_selectable_reward',
    `knight_selectable_reward` MEDIUMTEXT COMMENT 'knight_selectable_reward',
    `ranger_selectable_reward` MEDIUMTEXT COMMENT 'ranger_selectable_reward',
    `assassin_selectable_reward` MEDIUMTEXT COMMENT 'assassin_selectable_reward',
    `wizard_selectable_reward` MEDIUMTEXT COMMENT 'wizard_selectable_reward',
    `elementalist_selectable_reward` MEDIUMTEXT COMMENT 'elementalist_selectable_reward',
    `priest_selectable_reward` MEDIUMTEXT COMMENT 'priest_selectable_reward',
    `chanter_selectable_reward` MEDIUMTEXT COMMENT 'chanter_selectable_reward',
    `gunner_selectable_reward` MEDIUMTEXT COMMENT 'gunner_selectable_reward',
    `bard_selectable_reward` MEDIUMTEXT COMMENT 'bard_selectable_reward',
    `rider_selectable_reward` MEDIUMTEXT COMMENT 'rider_selectable_reward',
    `reward_item1_1` MEDIUMTEXT COMMENT 'reward_item1_1',
    `reward_item1_2` MEDIUMTEXT COMMENT 'reward_item1_2',
    `collect_item2` MEDIUMTEXT COMMENT 'collect_item2',
    `selectable_reward_item1_7` MEDIUMTEXT COMMENT 'selectable_reward_item1_7',
    `drop_monster_3` MEDIUMTEXT COMMENT 'drop_monster_3',
    `drop_item_3` MEDIUMTEXT COMMENT 'drop_item_3',
    `drop_prob_3` MEDIUMTEXT COMMENT 'drop_prob_3',
    `drop_each_member_3` MEDIUMTEXT COMMENT 'drop_each_member_3',
    `drop_monster_4` MEDIUMTEXT COMMENT 'drop_monster_4',
    `drop_item_4` MEDIUMTEXT COMMENT 'drop_item_4',
    `drop_prob_4` MEDIUMTEXT COMMENT 'drop_prob_4',
    `drop_each_member_4` MEDIUMTEXT COMMENT 'drop_each_member_4',
    `finished_quest_cond1` MEDIUMTEXT COMMENT 'finished_quest_cond1',
    `reward_item2_1` MEDIUMTEXT COMMENT 'reward_item2_1',
    `reward_gold2` MEDIUMTEXT COMMENT 'reward_gold2',
    `selectable_reward_item1_8` MEDIUMTEXT COMMENT 'selectable_reward_item1_8',
    `selectable_reward_item1_9` MEDIUMTEXT COMMENT 'selectable_reward_item1_9',
    `selectable_reward_item1_10` MEDIUMTEXT COMMENT 'selectable_reward_item1_10',
    `collect_item3` MEDIUMTEXT COMMENT 'collect_item3',
    `collect_item4` MEDIUMTEXT COMMENT 'collect_item4',
    `check_item1_2` MEDIUMTEXT COMMENT 'check_item1_2',
    `check_item1_3` MEDIUMTEXT COMMENT 'check_item1_3',
    `check_item1_4` MEDIUMTEXT COMMENT 'check_item1_4',
    `reward_item1_3` MEDIUMTEXT COMMENT 'reward_item1_3',
    `selectable_reward_item1_11` MEDIUMTEXT COMMENT 'selectable_reward_item1_11',
    `selectable_reward_item1_12` MEDIUMTEXT COMMENT 'selectable_reward_item1_12',
    `reward_abyss_point1` MEDIUMTEXT COMMENT 'reward_abyss_point1',
    `reward_item1_4` MEDIUMTEXT COMMENT 'reward_item1_4',
    `reward_item1_5` MEDIUMTEXT COMMENT 'reward_item1_5',
    `quest_work_item1` MEDIUMTEXT COMMENT 'quest_work_item1',
    `quest_work_item2` MEDIUMTEXT COMMENT 'quest_work_item2',
    `quest_work_item3` MEDIUMTEXT COMMENT 'quest_work_item3',
    `quest_work_item4` MEDIUMTEXT COMMENT 'quest_work_item4',
    `selectable_reward_item2_1` MEDIUMTEXT COMMENT 'selectable_reward_item2_1',
    `selectable_reward_item2_2` MEDIUMTEXT COMMENT 'selectable_reward_item2_2',
    `reward_title2` MEDIUMTEXT COMMENT 'reward_title2',
    `reward_item3_1` MEDIUMTEXT COMMENT 'reward_item3_1',
    `reward_gold3` MEDIUMTEXT COMMENT 'reward_gold3',
    `mobile_event` MEDIUMTEXT COMMENT 'mobile_event',
    `inventory_item_name1` MEDIUMTEXT COMMENT 'inventory_item_name1',
    `extra_category` MEDIUMTEXT COMMENT 'extra_category',
    `check_item2_1` MEDIUMTEXT COMMENT 'check_item2_1',
    `acquired_quest_cond1` MEDIUMTEXT COMMENT 'acquired_quest_cond1',
    `reward_repeat_count` MEDIUMTEXT COMMENT 'reward_repeat_count',
    `reward_gold_ext` MEDIUMTEXT COMMENT 'reward_gold_ext',
    `reward_item_ext_1` MEDIUMTEXT COMMENT 'reward_item_ext_1',
    `title` MEDIUMTEXT COMMENT 'title',
    `reward_item4_1` MEDIUMTEXT COMMENT 'reward_item4_1',
    `inventory_item_name2` MEDIUMTEXT COMMENT 'inventory_item_name2',
    `check_item3_1` MEDIUMTEXT COMMENT 'check_item3_1',
    `reward_gold4` MEDIUMTEXT COMMENT 'reward_gold4',
    `check_item4_1` MEDIUMTEXT COMMENT 'check_item4_1',
    `selectable_reward_item1_13` MEDIUMTEXT COMMENT 'selectable_reward_item1_13',
    `finished_quest_cond2` MEDIUMTEXT COMMENT 'finished_quest_cond2',
    `reward_item2_2` MEDIUMTEXT COMMENT 'reward_item2_2',
    `reward_item3_2` MEDIUMTEXT COMMENT 'reward_item3_2',
    `quest_repeat_cycle` MEDIUMTEXT COMMENT 'quest_repeat_cycle',
    `drop_monster_5` MEDIUMTEXT COMMENT 'drop_monster_5',
    `drop_item_5` MEDIUMTEXT COMMENT 'drop_item_5',
    `drop_prob_5` MEDIUMTEXT COMMENT 'drop_prob_5',
    `drop_each_member_5` MEDIUMTEXT COMMENT 'drop_each_member_5',
    `drop_monster_6` MEDIUMTEXT COMMENT 'drop_monster_6',
    `drop_item_6` MEDIUMTEXT COMMENT 'drop_item_6',
    `drop_prob_6` MEDIUMTEXT COMMENT 'drop_prob_6',
    `drop_each_member_6` MEDIUMTEXT COMMENT 'drop_each_member_6',
    `drop_monster_7` MEDIUMTEXT COMMENT 'drop_monster_7',
    `drop_item_7` MEDIUMTEXT COMMENT 'drop_item_7',
    `drop_prob_7` MEDIUMTEXT COMMENT 'drop_prob_7',
    `drop_each_member_7` MEDIUMTEXT COMMENT 'drop_each_member_7',
    `drop_monster_8` MEDIUMTEXT COMMENT 'drop_monster_8',
    `drop_item_8` MEDIUMTEXT COMMENT 'drop_item_8',
    `drop_prob_8` MEDIUMTEXT COMMENT 'drop_prob_8',
    `drop_each_member_8` MEDIUMTEXT COMMENT 'drop_each_member_8',
    `drop_monster_9` MEDIUMTEXT COMMENT 'drop_monster_9',
    `drop_item_9` MEDIUMTEXT COMMENT 'drop_item_9',
    `drop_prob_9` MEDIUMTEXT COMMENT 'drop_prob_9',
    `drop_each_member_9` MEDIUMTEXT COMMENT 'drop_each_member_9',
    `unfinished_quest_cond1` MEDIUMTEXT COMMENT 'unfinished_quest_cond1',
    `noacquired_quest_cond1` MEDIUMTEXT COMMENT 'noacquired_quest_cond1',
    `reward_abyss_point2` MEDIUMTEXT COMMENT 'reward_abyss_point2',
    `selectable_reward_item2_3` MEDIUMTEXT COMMENT 'selectable_reward_item2_3',
    `selectable_reward_item2_4` MEDIUMTEXT COMMENT 'selectable_reward_item2_4',
    `selectable_reward_item2_5` MEDIUMTEXT COMMENT 'selectable_reward_item2_5',
    `reward_abyss_point3` MEDIUMTEXT COMMENT 'reward_abyss_point3',
    `selectable_reward_item3_1` MEDIUMTEXT COMMENT 'selectable_reward_item3_1',
    `selectable_reward_item3_2` MEDIUMTEXT COMMENT 'selectable_reward_item3_2',
    `selectable_reward_item3_3` MEDIUMTEXT COMMENT 'selectable_reward_item3_3',
    `selectable_reward_item3_4` MEDIUMTEXT COMMENT 'selectable_reward_item3_4',
    `reward_title_ext` MEDIUMTEXT COMMENT 'reward_title_ext',
    `abyss_rank` MEDIUMTEXT COMMENT 'abyss_rank',
    `target_type` MEDIUMTEXT COMMENT 'target_type',
    `reward_extend_inventory1` MEDIUMTEXT COMMENT 'reward_extend_inventory1',
    `finished_quest_cond3` MEDIUMTEXT COMMENT 'finished_quest_cond3',
    `inventory_item_name3` MEDIUMTEXT COMMENT 'inventory_item_name3',
    `reward_abyss_point4` MEDIUMTEXT COMMENT 'reward_abyss_point4',
    `quest_permitted_worlds` MEDIUMTEXT COMMENT 'quest_permitted_worlds',
    `areas` MEDIUMTEXT COMMENT 'areas',
    `can_report` MEDIUMTEXT COMMENT 'can_report',
    `can_repeat_reward` MEDIUMTEXT COMMENT 'can_repeat_reward',
    `reward_exp_ext` MEDIUMTEXT COMMENT 'reward_exp_ext',
    `equiped_item_name1` MEDIUMTEXT COMMENT 'equiped_item_name1',
    `equiped_item_name2` MEDIUMTEXT COMMENT 'equiped_item_name2',
    `equiped_item_name3` MEDIUMTEXT COMMENT 'equiped_item_name3',
    `equiped_item_name4` MEDIUMTEXT COMMENT 'equiped_item_name4',
    `equiped_item_name5` MEDIUMTEXT COMMENT 'equiped_item_name5',
    `reward_extend_stigma1` MEDIUMTEXT COMMENT 'reward_extend_stigma1',
    `unfinished_quest_cond2` MEDIUMTEXT COMMENT 'unfinished_quest_cond2',
    `unfinished_quest_cond3` MEDIUMTEXT COMMENT 'unfinished_quest_cond3',
    `unfinished_quest_cond4` MEDIUMTEXT COMMENT 'unfinished_quest_cond4',
    `unfinished_quest_cond5` MEDIUMTEXT COMMENT 'unfinished_quest_cond5',
    `unfinished_quest_cond6` MEDIUMTEXT COMMENT 'unfinished_quest_cond6',
    `noacquired_quest_cond2` MEDIUMTEXT COMMENT 'noacquired_quest_cond2',
    `noacquired_quest_cond3` MEDIUMTEXT COMMENT 'noacquired_quest_cond3',
    `noacquired_quest_cond4` MEDIUMTEXT COMMENT 'noacquired_quest_cond4',
    `noacquired_quest_cond5` MEDIUMTEXT COMMENT 'noacquired_quest_cond5',
    `noacquired_quest_cond6` MEDIUMTEXT COMMENT 'noacquired_quest_cond6',
    `combineskill` MEDIUMTEXT COMMENT 'combineskill',
    `combine_skillpoint` MEDIUMTEXT COMMENT 'combine_skillpoint',
    `selectable_reward_item3_5` MEDIUMTEXT COMMENT 'selectable_reward_item3_5',
    `selectable_reward_item4_1` MEDIUMTEXT COMMENT 'selectable_reward_item4_1',
    `selectable_reward_item4_2` MEDIUMTEXT COMMENT 'selectable_reward_item4_2',
    `selectable_reward_item4_3` MEDIUMTEXT COMMENT 'selectable_reward_item4_3',
    `selectable_reward_item4_4` MEDIUMTEXT COMMENT 'selectable_reward_item4_4',
    `selectable_reward_item4_5` MEDIUMTEXT COMMENT 'selectable_reward_item4_5',
    `reward_gold5` MEDIUMTEXT COMMENT 'reward_gold5',
    `selectable_reward_item5_1` MEDIUMTEXT COMMENT 'selectable_reward_item5_1',
    `selectable_reward_item5_2` MEDIUMTEXT COMMENT 'selectable_reward_item5_2',
    `selectable_reward_item5_3` MEDIUMTEXT COMMENT 'selectable_reward_item5_3',
    `selectable_reward_item5_4` MEDIUMTEXT COMMENT 'selectable_reward_item5_4',
    `selectable_reward_item5_5` MEDIUMTEXT COMMENT 'selectable_reward_item5_5',
    `reward_gold6` MEDIUMTEXT COMMENT 'reward_gold6',
    `selectable_reward_item6_1` MEDIUMTEXT COMMENT 'selectable_reward_item6_1',
    `selectable_reward_item_ext_1` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_1',
    `selectable_reward_item_ext_2` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_2',
    `finished_quest_cond4` MEDIUMTEXT COMMENT 'finished_quest_cond4',
    `finished_quest_cond5` MEDIUMTEXT COMMENT 'finished_quest_cond5',
    `finished_quest_cond6` MEDIUMTEXT COMMENT 'finished_quest_cond6',
    `selectable_reward_item2_6` MEDIUMTEXT COMMENT 'selectable_reward_item2_6',
    `selectable_reward_item_ext_3` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_3',
    `selectable_reward_item_ext_4` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_4',
    `selectable_reward_item_ext_5` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_5',
    `selectable_reward_item_ext_6` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_6',
    `selectable_reward_item_ext_7` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_7',
    `selectable_reward_item_ext_8` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_8',
    `selectable_reward_item_ext_9` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_9',
    `selectable_reward_item_ext_10` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_10',
    `selectable_reward_item_ext_11` MEDIUMTEXT COMMENT 'selectable_reward_item_ext_11',
    `reward_cp1` MEDIUMTEXT COMMENT 'reward_cp1',
    `quest_repeat_count` MEDIUMTEXT COMMENT 'quest_repeat_count',
    `reward_score1` MEDIUMTEXT COMMENT 'reward_score1',
    `reward_score_ext` MEDIUMTEXT COMMENT 'reward_score_ext',
    `recipe_name` MEDIUMTEXT COMMENT 'recipe_name',
    `npcfaction_name` MEDIUMTEXT COMMENT 'npcfaction_name',
    `package_permitted` MEDIUMTEXT COMMENT 'package_permitted',
    `reward_glory_point1` MEDIUMTEXT COMMENT 'reward_glory_point1',
    `pcguild_level` MEDIUMTEXT COMMENT 'pcguild_level',
    `max_count_limitedquest` MEDIUMTEXT COMMENT 'max_count_limitedquest',
    `count_recover_limitedquest` MEDIUMTEXT COMMENT 'count_recover_limitedquest',
    `finished_quest_count1` MEDIUMTEXT COMMENT 'finished_quest_count1',
    `finished_quest_count2` MEDIUMTEXT COMMENT 'finished_quest_count2',
    `reward_item_ext_2` MEDIUMTEXT COMMENT 'reward_item_ext_2',
    `reward_item_ext_3` MEDIUMTEXT COMMENT 'reward_item_ext_3',
    `reward_item_ext_4` MEDIUMTEXT COMMENT 'reward_item_ext_4',
    `reward_challenge_task1` MEDIUMTEXT COMMENT 'reward_challenge_task1',
    `reward_item5_1` MEDIUMTEXT COMMENT 'reward_item5_1',
    `acquired_quest_cond2` MEDIUMTEXT COMMENT 'acquired_quest_cond2',
    `selectable_reward_item2_7` MEDIUMTEXT COMMENT 'selectable_reward_item2_7',
    `selectable_reward_item2_8` MEDIUMTEXT COMMENT 'selectable_reward_item2_8',
    `selectable_reward_item2_9` MEDIUMTEXT COMMENT 'selectable_reward_item2_9',
    `selectable_reward_item2_10` MEDIUMTEXT COMMENT 'selectable_reward_item2_10',
    `selectable_reward_item2_11` MEDIUMTEXT COMMENT 'selectable_reward_item2_11',
    `selectable_reward_item2_12` MEDIUMTEXT COMMENT 'selectable_reward_item2_12',
    `selectable_reward_item2_13` MEDIUMTEXT COMMENT 'selectable_reward_item2_13',
    `selectable_reward_item1_14` MEDIUMTEXT COMMENT 'selectable_reward_item1_14',
    `selectable_reward_item1_15` MEDIUMTEXT COMMENT 'selectable_reward_item1_15',
    `quest_cooltime` MEDIUMTEXT COMMENT 'quest_cooltime',
    `reward_abyss_op_point1` MEDIUMTEXT COMMENT 'reward_abyss_op_point1',
    `reward_exp_boost1` MEDIUMTEXT COMMENT 'reward_exp_boost1',
    `check_item2_2` MEDIUMTEXT COMMENT 'check_item2_2',
    `mentor_quest_type` MEDIUMTEXT COMMENT 'mentor_quest_type',
    `selectable_reward_item3_6` MEDIUMTEXT COMMENT 'selectable_reward_item3_6',
    `burningreward_item` MEDIUMTEXT COMMENT 'burningreward_item',
    `burningreward_time_begin` MEDIUMTEXT COMMENT 'burningreward_time_begin',
    `burningreward_duration` MEDIUMTEXT COMMENT 'burningreward_duration',
    `reward_dp1` MEDIUMTEXT COMMENT 'reward_dp1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED COMMENT = 'quest';

DROP TABLE IF EXISTS xmldb_suiyue.quest__fighter_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__fighter_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `fighter_selectable_item` VARCHAR(36) COMMENT 'fighter_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__fighter_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__knight_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__knight_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `knight_selectable_item` VARCHAR(36) COMMENT 'knight_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__knight_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__ranger_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__ranger_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `ranger_selectable_item` VARCHAR(37) COMMENT 'ranger_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__ranger_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__assassin_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__assassin_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `assassin_selectable_item` VARCHAR(36) COMMENT 'assassin_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__assassin_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__wizard_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__wizard_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `wizard_selectable_item` VARCHAR(36) COMMENT 'wizard_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__wizard_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__elementalist_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__elementalist_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `elementalist_selectable_item` VARCHAR(41) COMMENT 'elementalist_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__elementalist_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__priest_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__priest_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `priest_selectable_item` VARCHAR(37) COMMENT 'priest_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__priest_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__chanter_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__chanter_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `chanter_selectable_item` VARCHAR(40) COMMENT 'chanter_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__chanter_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__gunner_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__gunner_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `gunner_selectable_item` VARCHAR(36) COMMENT 'gunner_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__gunner_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__bard_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__bard_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `bard_selectable_item` VARCHAR(37) COMMENT 'bard_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__bard_selectable_reward__data';

DROP TABLE IF EXISTS xmldb_suiyue.quest__rider_selectable_reward__data;
CREATE TABLE xmldb_suiyue.quest__rider_selectable_reward__data (
    `id` VARCHAR(255) COMMENT '继承父id',
    `__order_index` INT NOT NULL DEFAULT 0 COMMENT '顺序索引',
    `rider_selectable_item` VARCHAR(36) COMMENT 'rider_selectable_item'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT = 'quest__rider_selectable_reward__data';

